### ISSUE TITLE
Verify that we manage all external domains

### ISSUE THREAD

**Issue by fricoben** [starknet-id/app.starknet.id#309]
## Description

Today for external domains (.braavos.stark and .xplorer.stark) we can't transfer the names on the front-end even though the contract permits you to do it. 

We could add a transfer_name button to add this possibility, Argent and Braavos are using the same implementation for this contract right now so we would just need to have their contract address. 

Here is their implementation https://github.com/starknet-id/resolver_delegation

## ToDo or Verify

- [ ] It's indexed and you see them on `/indentities`
- [ ] The image that showsup is the right one (argent, braavos or bonfida)
- [ ] You can transfer it and set it as main domain
